return {
  { item = "ash", icon = nil, stage = 1 },
  { item = "bonemeal", icon = nil, stage = 1 },
  { item = "borax", icon = nil, stage = 1 },
  { item = "boron-trioxide", icon = nil, stage = 1 },
  { item = "calcium-carbide", icon = nil, stage = 1 },
  { item = "chromium", icon = nil, stage = 1 },
  { item = "chromite-sand", icon = nil, stage = 1 },
  { item = "coal-dust", icon = nil, stage = 1 },
  { item = "coke", icon = nil, stage = 1 },
  { item = "fawogae", icon = nil, stage = 1 },
  { item = "fawogae-substrate", icon = nil, stage = 1 },
  { item = "gravel", icon = nil, stage = 1 },
  { item = "ground-sample01", icon = nil, stage = 1 },
  { item = "iron-oxide", icon = nil, stage = 1 },
  { item = "lens", icon = nil, stage = 1 },
  { item = "lime", icon = nil, stage = 1 },
  { item = "limestone", icon = nil, stage = 1 },
  { item = "nexelit-ore", icon = nil, stage = 1 },
  { item = "nexelit-plate", icon = nil, stage = 1 },
  { item = "organics", icon = nil, stage = 1 },
  { item = "pure-sand", icon = nil, stage = 1 },
  { item = "ralesia", icon = nil, stage = 1 },
  { item = "ralesia-seeds", icon = nil, stage = 1 },
  { item = "raw-borax", icon = nil, stage = 1 },
  { item = "rich-clay", icon = nil, stage = 1 },
  { item = "sand", icon = nil, stage = 1 },
  { item = "sand-casting", icon = nil, stage = 1 },
  { item = "tailings-dust", icon = nil, stage = 1 },
  { item = "treated-wood", icon = nil, stage = 1 },
  { item = "soil", icon = nil, stage = 1 },
  { item = "coarse", icon = nil, stage = 1 },

  { item = "kevlar", icon = nil, stage = 2 },
  { item = "nbfe-alloy", icon = nil, stage = 2 },
  { item = "nichrome", icon = nil, stage = 2 },
  { item = "niobium-ore", icon = nil, stage = 2 },
  { item = "niobium-plate", icon = nil, stage = 2 },

  { item = "fuelrod-mk01", icon = nil, stage = 3 }
}
