return {
  { item = "molybdenite-dust", icon = nil, stage = 1 },

  { item = "nbti-alloy", icon = nil, stage = 2 },
  { item = "molybdenum-plate", icon = nil, stage = 2 },
  { item = "control-unit", icon = nil, stage = 2 },
  { item = "pure-kimberlite-grade2", icon = nil, stage = 2 },
  { item = "boron-mixture", icon = nil, stage = 2 },
  { item = "boron", icon = nil, stage = 2 },
  { item = "sodium-chlorate", icon = nil, stage = 2 },
  { item = "molybdenum-concentrate", icon = nil, stage = 2 },
  { item = "nexelit-matrix", icon = nil, stage = 2 },
  { item = "nenbit-matrix", icon = nil, stage = 2 },
  { item = "ferrite", icon = nil, stage = 2 },
  { item = "nuclear-sample", icon = nil, stage = 2 },

  { item = "boron-carbide", icon = nil, stage = 3 },
  { item = "super-alloy", icon = nil, stage = 3 },
  { item = "wall-shield", icon = nil, stage = 3 },
  { item = "regolite-rock", icon = nil, stage = 3 },
  { item = "processed-rejects", icon = nil, stage = 3 },
  { item = "kimberlite-rock", iconName = "ores/kimberlite-rock", icon = nil, stage = 3 },
  { item = "kimberlite-residue", icon = nil, stage = 3 },
  { item = "kimberlite-rejects", icon = nil, stage = 3 },
  { item = "diamond-reject", icon = nil, stage = 3 },
  { item = "crushed-kimberlite", icon = nil, stage = 3 },
  { item = "kimberlite-grade2", icon = nil, stage = 3 },
  { item = "kimberlite-grade3", icon = nil, stage = 3 },
  { item = "molybdenum-ore", iconName = "molybdenum", icon = nil, stage = 3 },
  { item = "blanket-chassi", icon = nil, stage = 3 },
  { item = "b2o3-dust", icon = nil, iconName = "boron-trioxide-dust", stage = 3 },
  { item = "blanket", icon = nil, stage = 3 },
  { item = "regolite-dust", icon = nil, stage = 3 },
  { item = "methyl-acrylate", icon = nil, stage = 3 },
  { item = "kmauts-ration", icon = nil, stage = 3 },
  { item = "calcinates", icon = nil, stage = 3 },
  { item = "serine", icon = nil, stage = 3 },
  { item = "vanadium-oxide", icon = nil, stage = 3 },
  { item = "crushed-regolite", icon = nil, stage = 3 },
  { item = "powdered-regolite", icon = nil, stage = 3 },
  { item = "agzn-alloy", icon = nil, stage = 3 },
  { item = "silver-foam", icon = nil, stage = 3 },
  { item = "sc-wire", icon = nil, iconName = "superconducting-wire", stage = 3 },
  { item = "sc-coil", icon = nil, iconName = "superconducting-coil", stage = 3 },
  { item = "magnetic-core", icon = nil, stage = 3 },
  { item = "lead-container", icon = nil, stage = 3 },
  { item = "reinforced-wall-shield", icon = nil, iconName = "rwall-shield", stage = 3 },
  { item = "divertor", icon = nil, stage = 3 },
  { item = "deposited-core", icon = nil, iconName = "deposited-vcore", stage = 3 },
  { item = "coil-core", icon = nil, stage = 3 },
  { item = "coated-container", icon = nil, stage = 3 },
  { item = "sc-unit", icon = nil, iconName = "magnetic-unit", stage = 3 },
  { item = "crude-diamond", icon = nil, stage = 3 },
  { item = "diamond", icon = nil, stage = 3 },
  { item = "washed-diamond", icon = nil, stage = 3 }
}
